<?php
/**
 * This file is only required for type-hinting in your IDE when using a modern version of Joomla! which has replaced
 * core API classes with namespaced ones.
 *
 * Please keep in mind that Joomla! 4.0 and later will no longer include JCryptCipher3Des.
 *
 * This file was automatically generated by 'TypeHint Helper for Joomla!' (https://github.com/nikosdion/joomlatypehints)
 * for Joomla! version 3.8.0
 *
 * @since       3.8.0
 * @deprecated  4.0
 */
class JCryptCipher3Des extends \Joomla\CMS\Crypt\Cipher\TripleDesCipher {}