<?php
/**
 * This file is only required for type-hinting in your IDE when using a modern version of Joomla! which has replaced
 * core API classes with namespaced ones.
 *
 * Please keep in mind that Joomla! 6.0 and later will no longer include JFeed.
 *
 * This file was automatically generated by 'TypeHint Helper for Joomla!' (https://github.com/nikosdion/joomlatypehints)
 * for Joomla! version 4.4.0
 *
 * @deprecated  6.0
 */
class JFeed extends \Joomla\CMS\Feed\Feed {}