<?php
/**
 * This file is only required for type-hinting in your IDE when using a modern version of Joomla! which has replaced
 * core API classes with namespaced ones.
 *
 * Please keep in mind that Joomla! 5.0 and later will no longer include JFormFieldHelpsite.
 *
 * This file was automatically generated by 'TypeHint Helper for Joomla!' (https://github.com/nikosdion/joomlatypehints)
 * for Joomla! version 3.10.0
 *
 * @deprecated  5.0
 */
class JFormFieldHelpsite extends \Joomla\CMS\Form\Field\HelpsiteField {}